export const SET_DECK_SIZE = 'SET_DECK_SIZE';
export const START_NEW_GAME = 'START_NEW_GAME';
export const FLIP_CARD_FIRST = 'FLIP_CARD_FIRST';
export const FLIP_CARD_SECOND_CORRECT = 'FLIP_CARD_SECOND_CORRECT';
export const FLIP_CARD_SECOND_FALSE = 'FLIP_CARD_SECOND_FALSE';
